#!/usr/bin/env python3
"""Emit Sources/CPNG/gen/swift_stubs.c.

Every function in the published libpng API that does not yet have a real
implementation gets a definition here with its exact declared prototype, so the
library exports the complete symbol set from the first buildable commit and can
be dropped in place of the reference build immediately.  A stub reports the gap
through the normal error path rather than returning a wrong answer quietly.

scripts/implemented.txt lists the names that are implemented for real, in C or
in Swift.  Moving a name into that file is what retires its stub; forgetting to
is a duplicate symbol at link time, so the two cannot drift apart.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
API = ROOT / "scripts" / "api.json"
IMPLEMENTED = ROOT / "scripts" / "implemented.txt"
OUTPUT = ROOT / "Sources" / "CPNG" / "gen" / "swift_stubs.c"

HEADER = """/* swift_stubs.c - generated by scripts/gen_stubs.py; do not edit
 *
 * Placeholder definitions for the parts of the libpng API that this library
 * does not implement yet.  They exist so that the export table is complete and
 * clients link and load against us unchanged; each one reports the gap instead
 * of returning a plausible-looking wrong answer.
 *
 * Retire a stub by adding its name to scripts/implemented.txt and regenerating.
 */

#include "swift_internal.h"

#include <stdio.h>
#include <stdlib.h>

#if defined(__clang__) || defined(__GNUC__)
#  pragma GCC diagnostic ignored "-Wunused-parameter"
#endif

/* Reached only by stubs with no png_struct to report through. */
static void
swift_unimplemented_fatal(const char *name)
{
   fprintf(stderr, "libpng error: %s is not implemented\\n", name);
   fflush(stderr);
   abort();
}
"""

# The first parameter identifies the reporting channel.  A png_struct gives us
# the client's error handler; the simplified API reports through png_image; the
# handful of pure helpers have nothing to report through at all.
STRUCT_PARAM = re.compile(r"^png_(?:const_)?struct(?:rp|p)\s+(\w+)")
IMAGE_PARAM = re.compile(r"^png_(?:const_)?imagep\s+(\w+)")


def split_parameters(args: str) -> list[str]:
    inner = args.strip()[1:-1].strip()
    if not inner or inner == "void":
        return []

    parameters = []
    depth = 0
    start = 0
    for index, character in enumerate(inner):
        if character in "([":
            depth += 1
        elif character in ")]":
            depth -= 1
        elif character == "," and depth == 0:
            parameters.append(inner[start:index].strip())
            start = index + 1
    parameters.append(inner[start:].strip())
    return parameters


def is_unnamed(parameter: str) -> bool:
    """Whether a parameter declaration omits its identifier.

    A named parameter always has a type and a name, so at least two tokens; a
    declaration that is a single token, or that ends in a pointer star, has only
    a type.  Function-pointer parameters carry their name inside parentheses and
    are always named.
    """
    if "(" in parameter:
        return False
    return len(parameter.split()) == 1 or parameter.endswith("*")


def name_parameters(args: str) -> str:
    """Give every parameter an identifier.

    png.h omits the name on a few declarations, which is legal in a prototype but
    a C23 extension in a definition, so the generated file supplies one.
    """
    parameters = split_parameters(args)
    if not parameters:
        return "(void)"

    named = [
        f"{parameter} swift_arg{index}" if is_unnamed(parameter) else parameter
        for index, parameter in enumerate(parameters)
    ]
    return "(" + ", ".join(named) + ")"


def first_parameter(args: str) -> str:
    parameters = split_parameters(args)
    return parameters[0] if parameters else ""


def body(function: dict, args: str) -> list[str]:
    """The stub body, reporting through whatever channel the signature offers.

    `args` is the parameter list after naming, so the identifiers referred to here
    are the ones the generated definition actually declares.
    """
    name = function["name"]
    returns_value = function["return"] != "void"
    parameter = first_parameter(args)

    struct = STRUCT_PARAM.match(parameter)
    if struct:
        # png_error is declared noreturn, so no return statement is needed.
        return [f'   png_error({struct.group(1)}, "{name} is not implemented");']

    image = IMAGE_PARAM.match(parameter)
    if image:
        lines = [f'   swift_unimplemented_fatal("{name}");']
        if returns_value:
            lines.append(f"   return ({function['return']})0;")
        return lines

    lines = [f'   swift_unimplemented_fatal("{name}");']
    if returns_value:
        lines.append(f"   return ({function['return']})0;")
    return lines


def main() -> None:
    functions = json.loads(API.read_text())
    implemented = {
        line.split("#", 1)[0].strip()
        for line in IMPLEMENTED.read_text().splitlines()
        if line.split("#", 1)[0].strip()
    }

    known = {function["name"] for function in functions}
    unknown = implemented - known
    if unknown:
        sys.exit(f"implemented.txt names functions absent from api.json: {sorted(unknown)}")

    pending = [f for f in functions if f["name"] not in implemented]

    parts = [HEADER]
    for function in pending:
        args = name_parameters(function["args"])
        parts.append(
            "\n{ret} PNGAPI\n{name}{args}\n{{\n{body}\n}}\n".format(
                ret=function["return"],
                name=function["name"],
                args=args,
                body="\n".join(body(function, args)),
            )
        )

    if not pending:
        parts.append(
            "\n/* Every published function is implemented; nothing to stub. */\n"
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("".join(parts))
    print(
        f"wrote {len(pending)} stubs to {OUTPUT.relative_to(ROOT)} "
        f"({len(implemented)} of {len(functions)} implemented)"
    )


if __name__ == "__main__":
    main()
